/**
 * Role-specific application column lists.
 * Keep final document paths / WhatsApp internals out of customer & partner shapes.
 */

/** Safe for customer dashboards — no paths, WhatsApp, or internal notes. */
export const CUSTOMER_APPLICATION_SELECT = [
  "id",
  "user_id",
  "customer_id",
  "service_id",
  "service_slug",
  "service_name",
  "amount",
  "total_amount",
  "status",
  "payment_status",
  "form_data",
  "customer_details",
  "customer_message",
  "customer_note",
  "customer_mobile",
  "customer_email",
  "submitted_at",
  "paid_at",
  "completed_at",
  "created_at",
  "updated_at",
  "wallet_used_amount",
  "wallet_redeemed_amount",
  "fresh_payable_amount",
  "application_code",
].join(", ");

/** Safe for Digi Partner / agent UIs. */
export const PARTNER_APPLICATION_SELECT = [
  "id",
  "user_id",
  "customer_id",
  "agency_partner_id",
  "agent_id",
  "assigned_agent_id",
  "created_by",
  "created_by_agent_id",
  "service_id",
  "service_slug",
  "service_name",
  "amount",
  "total_amount",
  "status",
  "payment_status",
  "form_data",
  "customer_details",
  "customer_mobile",
  "commission_amount",
  "submitted_at",
  "paid_at",
  "completed_at",
  "created_at",
  "updated_at",
  "application_code",
  "application_source",
  "source",
  "submitted_by_role",
].join(", ");

/**
 * Admin operational select — prefer this over `*`.
 * Includes post-migration columns; callers should fall back to ADMIN_APPLICATION_SELECT_LEGACY.
 */
export const ADMIN_APPLICATION_SELECT = [
  "id",
  "user_id",
  "customer_id",
  "agency_partner_id",
  "agent_id",
  "assigned_agent_id",
  "assigned_to",
  "created_by",
  "created_by_agent_id",
  "service_id",
  "service_slug",
  "service_name",
  "amount",
  "total_amount",
  "status",
  "payment_status",
  "form_data",
  "customer_details",
  "customer_mobile",
  "customer_email",
  "customer_message",
  "customer_note",
  "internal_notes",
  "admin_note",
  "commission_amount",
  "cashback_enabled",
  "cashback_amount",
  "cashback_expiry_days",
  "cashback_credited_at",
  "cashback_eligible_amount",
  "wallet_used_amount",
  "wallet_redeemed_amount",
  "fresh_payable_amount",
  "real_payment_amount",
  "razorpay_order_id",
  "razorpay_payment_id",
  "payment_screenshot_url",
  "payment_screenshot_path",
  "final_document_id",
  "final_document_name",
  "final_document_path",
  "completed_document_storage_path",
  "completed_at",
  "priority",
  "due_at",
  "whatsapp_final_delivery_status",
  "whatsapp_final_delivered_at",
  "application_source",
  "source_channel",
  "source",
  "submitted_by_role",
  "submitted_at",
  "paid_at",
  "created_at",
  "updated_at",
  "application_code",
].join(", ");

/** Pre-migration admin columns (paths kept server-side only; no new ops columns). */
export const ADMIN_APPLICATION_SELECT_LEGACY = [
  "id",
  "user_id",
  "customer_id",
  "agency_partner_id",
  "agent_id",
  "assigned_agent_id",
  "assigned_to",
  "created_by",
  "created_by_agent_id",
  "service_id",
  "service_slug",
  "service_name",
  "amount",
  "total_amount",
  "status",
  "payment_status",
  "form_data",
  "customer_details",
  "customer_mobile",
  "customer_email",
  "customer_message",
  "customer_note",
  "internal_notes",
  "admin_note",
  "commission_amount",
  "cashback_enabled",
  "cashback_amount",
  "cashback_expiry_days",
  "cashback_credited_at",
  "wallet_used_amount",
  "wallet_redeemed_amount",
  "fresh_payable_amount",
  "real_payment_amount",
  "razorpay_order_id",
  "razorpay_payment_id",
  "payment_screenshot_url",
  "payment_screenshot_path",
  "final_document_name",
  "final_document_path",
  "final_document_url",
  "completed_document_url",
  "completed_document_storage_path",
  "completed_at",
  "application_source",
  "source_channel",
  "source",
  "submitted_by_role",
  "submitted_at",
  "paid_at",
  "created_at",
  "updated_at",
  "application_code",
].join(", ");

/** Fields that must never be returned to customer/partner application payloads. */
export const SENSITIVE_APPLICATION_FIELDS = [
  "final_document_path",
  "final_document_url",
  "final_document_id",
  "completed_document_url",
  "completed_document_storage_path",
  "internal_notes",
  "admin_note",
  "whatsapp_final_delivery_status",
  "whatsapp_final_delivered_at",
  "priority",
  "due_at",
] as const;

export function stripSensitiveApplicationFields<T extends Record<string, unknown>>(row: T): T {
  const next = { ...row } as Record<string, unknown>;
  for (const key of SENSITIVE_APPLICATION_FIELDS) {
    delete next[key];
  }
  // Never leak signed/public final URLs even if present under alternate keys.
  next.final_document_url = null;
  next.completed_document_url = null;
  return next as T;
}
