// Generated by scripts/build-print-station.mjs — do not edit by hand.
// Mirrors print-station/lib/version.mjs so the download's filename and
// the version the program logs can never disagree.

export const PRINT_STATION_VERSION = "1.3.0";
